[workspace]
resolver = "2"
members = [
    "projects/hello_cargo",
    "projects/guessing_game",
    "projects/variables",
    "projects/data_types",
    "projects/control_flow",
    "projects/temperature_conversion",
    "projects/fibonacci",
]
